import "../globals.css";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import AuthWrapper from "@/components/AuthWrapper";
export const metadata = {
  title: "House App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <AuthWrapper>
    <html lang="en">
      <body>

      <Header />
          <main className='mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8'>
            {children}
          </main>
        <ToastContainer></ToastContainer>
            </body>
    </html>
      </AuthWrapper>
  );
}
